USE [master]
GO

/****** Object:  Database [QuanLyPhongTro]    Script Date: 7/10/2020 8:59:47 AM ******/
DROP DATABASE [QuanLyPhongTro]
GO

/****** Object:  Database [QuanLyPhongTro]    Script Date: 7/10/2020 8:59:47 AM ******/
CREATE DATABASE [QuanLyPhongTro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyPhongTro', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QuanLyPhongTro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyPhongTro_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QuanLyPhongTro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [QuanLyPhongTro] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyPhongTro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyPhongTro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyPhongTro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyPhongTro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QuanLyPhongTro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyPhongTro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLyPhongTro] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyPhongTro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyPhongTro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyPhongTro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyPhongTro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLyPhongTro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyPhongTro] SET QUERY_STORE = OFF
GO

USE [QuanLyPhongTro]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [QuanLyPhongTro] SET  READ_WRITE 
GO

create table KHACHHANG(
	idKhachHang int Identity  primary key,
	hoTenKhachHang varchar(100), 
	thongTinCaNhan varchar(100),
	lienLac varchar(100), 
	ghiChu varchar(100), 
	idHopDong int,
)

create table HOPDONG(
	idHopdong int Identity  primary key,
	bieuPhiTuyBien int, 
	bieuPhiGiaPhong int,
	idPhieuThu int, 
	idPhongTro int,
	idKhachHang int,
	ghiChu varchar(100),
)

create table PHIEUTHU(
	idPhieuThu int Identity  primary key,
	phiTuyBien int, 
	phiThuePhong int,
	tienNuoc int, 
	tienDien int, 
	ghiChu varchar(100),
)

create table PHONGTRO(
	idPhongTro int Identity  primary key,
	tenPhong varchar(100), 
	giaKhuyenNghi int,
	tinhTrangPhong varchar(100), 
	chiSoNuocHienHanh int, 
	chiSoDienHienHanh varchar(100),
)

create table ACCOUNT(
	id int Identity  primary key,
	taiKhoan varchar(100), 
	matKhau varchar(100),
)

create table PHIEUCHI(
	idPhieuChi int Identity  primary key,
	tienDien int, 
	tienNuoc int,
	tienKhac int,
)
--KhachHang
ALTER TABLE KHACHHANG
ADD FOREIGN KEY (idHopDong) REFERENCES HOPDONG(idHopDong)
--Hop Dong 
ALTER TABLE HOPDONG
ADD FOREIGN KEY (idPhieuThu) REFERENCES PHIEUTHU(idPhieuThu)
ALTER TABLE HOPDONG
ADD FOREIGN KEY (idPhongTro) REFERENCES PHONGTRO(idPhongTro);
ALTER TABLE HOPDONG
ADD FOREIGN KEY (idKhachHang) REFERENCES KHACHHANG(idKhachHang);